apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "signalr.fullname" . }}-config
data:
  appsettings.json: |-
    {
        "Logging" : {
            "LogLevel": {
            "Default": "Information",
            "Microsoft": "Warning",
            "Microsoft.Hosting.Lifetime": "Information"
            }
        },
        "AllowedHosts": "*",
        "Redis": "127.0.0.1:6379"
    }
