apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "signalr.fullname" . }}-config
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*",
      "SignalRRedis": "{{ .Values.signalr.signalRRedisConnectionString }}",
      "Redis": "{{ .Values.signalr.redisConnectionString }}",
      "SUGARCHAT_SIGNAL_HUB_URL": "{{ .Values.signalr.SUGARCHAT_SIGNAL_HUB_URL }}",
      "ServerClientKey": "{{ .Values.signalr.ServerClientKey }}"
    }

